version: '3'

services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: php-sample-php
    volumes:
    - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    - ./src:/apps/php-sample
    ports:
    - 8080:8080
    working_dir: /apps/php-sample
    command: php -S 0.0.0.0:8080

  db:
    image: mysql:8
    container_name: php-sample-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample
      MYSQL_USER: sample
      MYSQL_PASSWORD: sample
      TZ: 'Asia/Tokyo'
    command: mysqld --port 3300
    volumes:
    - ./docker/db/data:/var/lib/mysql
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./sql:/docker-entrypoint-initdb.d/sql
    ports:
    - 3300:3300
